version: '2'

services:
  examaster:
    image: vagsai/exaremedist:v1
    environment:
      - MASTER_FLAG=master
      - CONSULURL=83.212.100.72:8500
      - EXA_WORKERS_WAIT=2
      - RAWUSERNAME=federation
      - RAWPASSWORD=federation
      - RAWHOST=raw-ui
      - RAWPORT=5555
      - RAWENDPOINT=query
      - RAWRESULTS=all
      - RAWDATAKEY=output #query used with output, query-start with data 
    ports:
      - "9090:9090"

  exaworker1:
    image:  vagsai/exaremedist:v1
    environment:
      - CONSULURL=83.212.100.72:8500
      - RAWUSERNAME=federation
      - RAWPASSWORD=federation
      - RAWHOST=raw-ui
      - RAWPORT=5555
      - RAWENDPOINT=query
      - RAWRESULTS=all
      - RAWDATAKEY=output #query used with output, query-start with data

  exaworker2:
    image:  vagsai/exaremedist:v1
    environment:
      - CONSULURL=83.212.100.72:8500
      - RAWUSERNAME=federation
      - RAWPASSWORD=federation
      - RAWHOST=raw-ui
      - RAWPORT=5555
      - RAWENDPOINT=query
      - RAWRESULTS=all
      - RAWDATAKEY=output #query used with output, query-start with data     
